"""Add user_id field to User model

Revision ID: 38ce4a828c7e
Revises: f19fc4b25b94
Create Date: 2025-06-09 20:39:26.510198

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "38ce4a828c7e"
down_revision: Union[str, None] = "f19fc4b25b94"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
