"""add_email_verification_and_approval

Revision ID: 43b7083f77c0
Revises: 31cb70510c76
Create Date: 2025-10-16 10:25:57.341757

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "43b7083f77c0"
down_revision: Union[str, None] = "31cb70510c76"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("email_verified", sa.Boolean(), nullable=True))
    op.add_column(
        "users",
        sa.Column("email_verification_token", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "users", sa.Column("email_verification_sent_at", sa.DateTime(), nullable=True)
    )
    op.add_column("users", sa.Column("is_approved", sa.Boolean(), nullable=True))
    op.add_column(
        "users", sa.Column("approval_token", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "users", sa.Column("approval_request_sent_at", sa.DateTime(), nullable=True)
    )
    op.add_column("users", sa.Column("approved_at", sa.DateTime(), nullable=True))
    op.add_column(
        "users", sa.Column("approved_by", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "approved_by")
    op.drop_column("users", "approved_at")
    op.drop_column("users", "approval_request_sent_at")
    op.drop_column("users", "approval_token")
    op.drop_column("users", "is_approved")
    op.drop_column("users", "email_verification_sent_at")
    op.drop_column("users", "email_verification_token")
    op.drop_column("users", "email_verified")
    # ### end Alembic commands ###
