"""add_email_verification_and_approval

Revision ID: 43b7083f77c0
Revises: 31cb70510c76
Create Date: 2025-10-16 10:25:57.341757

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "43b7083f77c0"
down_revision: Union[str, None] = "31cb70510c76"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = inspector.get_table_names()

    def get_cols(table):
        if table not in existing_tables:
            return []
        return [c['name'] for c in inspector.get_columns(table)]

    def get_fks(table):
        if table not in existing_tables:
            return []
        return [f['name'] for f in inspector.get_foreign_keys(table)]

    def get_indexes(table):
        if table not in existing_tables:
            return []
        return [i['name'] for i in inspector.get_indexes(table)]

    bind = op.get_bind()
    inspector = sa.inspect(bind)

    def get_cols(table):
        return [c["name"] for c in inspector.get_columns(table)]

    cols = get_cols("users")

    if "email_verified" not in cols:
        op.add_column(
            "users",
            sa.Column("email_verified", sa.Boolean(), nullable=True),
        )

    if "email_verification_token" not in cols:
        op.add_column(
            "users",
            sa.Column(
                "email_verification_token",
                sa.String(length=255),
                nullable=True,
            ),
        )

    if "email_verification_sent_at" not in cols:
        op.add_column(
            "users",
            sa.Column(
                "email_verification_sent_at",
                sa.DateTime(),
                nullable=True,
            ),
        )

    if "is_approved" not in cols:
        op.add_column(
            "users",
            sa.Column("is_approved", sa.Boolean(), nullable=True),
        )

    if "approval_token" not in cols:
        op.add_column(
            "users",
            sa.Column(
                "approval_token",
                sa.String(length=255),
                nullable=True,
            ),
        )

    if "approval_request_sent_at" not in cols:
        op.add_column(
            "users",
            sa.Column(
                "approval_request_sent_at",
                sa.DateTime(),
                nullable=True,
            ),
        )

    if "approved_at" not in cols:
        op.add_column(
            "users",
            sa.Column("approved_at", sa.DateTime(), nullable=True),
        )

    if "approved_by" not in cols:
        op.add_column(
            "users",
            sa.Column("approved_by", sa.String(length=255), nullable=True),
        )

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "approved_by")
    op.drop_column("users", "approved_at")
    op.drop_column("users", "approval_request_sent_at")
    op.drop_column("users", "approval_token")
    op.drop_column("users", "is_approved")
    op.drop_column("users", "email_verification_sent_at")
    op.drop_column("users", "email_verification_token")
    op.drop_column("users", "email_verified")
    # ### end Alembic commands ###
