"""added 'assistant_parameters' column to table sessions

Revision ID: 49474d944ee9
Revises: f2de7958d541
Create Date: 2025-06-03 18:01:25.786520

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "49474d944ee9"
down_revision: Union[str, None] = "f2de7958d541"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sessions",
        sa.Column(
            "assistant_parameters",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
    )
    op.drop_column("sessions", "ai_instructions")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sessions",
        sa.Column("ai_instructions", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.drop_column("sessions", "assistant_parameters")
    # ### end Alembic commands ###
