"""changed structure

Revision ID: 4a7179f3a9fe
Revises: b92063665e8a
Create Date: 2025-06-09 19:53:48.948082

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4a7179f3a9fe"
down_revision: Union[str, None] = "b92063665e8a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # First, drop foreign key constraints that reference tables we want to drop
    op.drop_constraint("sessions_presentation_id_fkey", "sessions", type_="foreignkey")

    # Now we can safely drop the tables
    op.drop_table("presentations")
    op.drop_table("slides")

    # Add new columns and constraints for session_runs
    op.add_column("session_runs", sa.Column("user_id", sa.UUID(), nullable=False))
    op.add_column(
        "session_runs",
        sa.Column(
            "session_run_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
    )
    op.add_column("session_runs", sa.Column("start_time", sa.DateTime(), nullable=True))
    op.add_column("session_runs", sa.Column("end_time", sa.DateTime(), nullable=True))
    op.create_foreign_key(None, "session_runs", "users", ["user_id"], ["id"])
    op.drop_column("session_runs", "ended_at")
    op.drop_column("session_runs", "run_metadata")
    op.drop_column("session_runs", "started_at")

    # Modify sessions table
    op.add_column("sessions", sa.Column("user_id", sa.UUID(), nullable=False))
    op.add_column(
        "sessions",
        sa.Column(
            "presentation_details",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
    )
    op.add_column(
        "sessions",
        sa.Column(
            "slides_details", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.alter_column(
        "sessions", "class_name", existing_type=sa.VARCHAR(length=200), nullable=True
    )
    op.create_foreign_key(None, "sessions", "users", ["user_id"], ["id"])
    op.drop_column("sessions", "presentation_id")
    op.drop_column("sessions", "processed_slides")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sessions",
        sa.Column(
            "processed_slides",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "sessions",
        sa.Column("presentation_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "sessions", type_="foreignkey")
    op.create_foreign_key(
        "sessions_presentation_id_fkey",
        "sessions",
        "presentations",
        ["presentation_id"],
        ["id"],
    )
    op.alter_column(
        "sessions", "class_name", existing_type=sa.VARCHAR(length=200), nullable=False
    )
    op.drop_column("sessions", "slides_details")
    op.drop_column("sessions", "presentation_details")
    op.drop_column("sessions", "user_id")
    op.add_column(
        "session_runs",
        sa.Column(
            "started_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "session_runs",
        sa.Column(
            "run_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "session_runs",
        sa.Column(
            "ended_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.drop_constraint(None, "session_runs", type_="foreignkey")
    op.drop_column("session_runs", "end_time")
    op.drop_column("session_runs", "start_time")
    op.drop_column("session_runs", "session_run_metadata")
    op.drop_column("session_runs", "user_id")
    op.create_table(
        "slides",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("session_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("slide_number", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("title", sa.VARCHAR(length=500), autoincrement=False, nullable=True),
        sa.Column("content", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "image_path", sa.VARCHAR(length=500), autoincrement=False, nullable=True
        ),
        sa.Column(
            "thumbnail_path", sa.VARCHAR(length=500), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["session_id"], ["sessions.id"], name="slides_session_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="slides_pkey"),
    )
    op.create_table(
        "presentations",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "filename", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column(
            "file_path", sa.VARCHAR(length=500), autoincrement=False, nullable=False
        ),
        sa.Column("file_size", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "file_type", sa.VARCHAR(length=10), autoincrement=False, nullable=False
        ),
        sa.Column(
            "upload_timestamp",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "processing_status",
            postgresql.ENUM(
                "PENDING", "PROCESSING", "COMPLETED", "FAILED", name="processingstatus"
            ),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.PrimaryKeyConstraint("id", name="presentations_pkey"),
    )
    # ### end Alembic commands ###
