"""changes to session/slide

Revision ID: 76f1bb55dd5d
Revises: 49474d944ee9
Create Date: 2025-06-04 15:12:25.491315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '76f1bb55dd5d'
down_revision: Union[str, None] = '49474d944ee9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('processed_slides', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('sessions', 'processed_content')
    op.drop_column('slides', 'teaching_notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slides', sa.Column('teaching_notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('sessions', sa.Column('processed_content', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('sessions', 'processed_slides')
    # ### end Alembic commands ###
