"""changes

Revision ID: 7e9bdf9d4379
Revises: a8aba4622ffc
Create Date: 2025-06-11 15:15:54.182460

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7e9bdf9d4379"
down_revision: Union[str, None] = "a8aba4622ffc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = inspector.get_table_names()

    def get_cols(table):
        if table not in existing_tables:
            return []
        return [c['name'] for c in inspector.get_columns(table)]

    def get_fks(table):
        if table not in existing_tables:
            return []
        return [f['name'] for f in inspector.get_foreign_keys(table)]

    def get_indexes(table):
        if table not in existing_tables:
            return []
        return [i['name'] for i in inspector.get_indexes(table)]

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "session_runs",
        "session_run_id",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=50),
        existing_nullable=False,
    )
    op.alter_column(
        "sessions",
        "session_id",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=50),
        existing_nullable=False,
    )
    if 'email' not in get_cols('users'):
        op.add_column("users", sa.Column("email", sa.String(length=255), nullable=False))
    op.add_column(
        "users", sa.Column("password_hash", sa.String(length=255), nullable=False)
    )
    op.add_column(
        "users", sa.Column("first_name", sa.String(length=100), nullable=False)
    )
    op.add_column(
        "users", sa.Column("last_name", sa.String(length=100), nullable=False)
    )
    if 'role' not in get_cols('users'):
        op.add_column("users", sa.Column("role", sa.String(length=50), nullable=False))
    op.create_unique_constraint(None, "users", ["email"])
    if 'password' in get_cols('users'):
        op.drop_column("users", "password")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "password", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "role")
    op.drop_column("users", "last_name")
    op.drop_column("users", "first_name")
    op.drop_column("users", "password_hash")
    op.drop_column("users", "email")
    op.alter_column(
        "sessions",
        "session_id",
        existing_type=sa.String(length=50),
        type_=sa.VARCHAR(length=100),
        existing_nullable=False,
    )
    op.alter_column(
        "session_runs",
        "session_run_id",
        existing_type=sa.String(length=50),
        type_=sa.VARCHAR(length=100),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
