"""added vision instructions to slides table

Revision ID: 82af9c044e6e
Revises: 8a3ed7e3af56
Create Date: 2025-06-27 12:00:27.389041

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "82af9c044e6e"
down_revision: Union[str, None] = "8a3ed7e3af56"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
