"""added columns to session

Revision ID: 9077ce18ff15
Revises: 8b5728efb47d
Create Date: 2025-06-29 22:36:30.268715

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9077ce18ff15"
down_revision: Union[str, None] = "8b5728efb47d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sessions", sa.Column("session_number", sa.Integer(), nullable=True))
    op.add_column("sessions", sa.Column("session_date", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sessions", "session_date")
    op.drop_column("sessions", "session_number")
    # ### end Alembic commands ###
