"""added columns to session

Revision ID: 9077ce18ff15
Revises: 8b5728efb47d
Create Date: 2025-06-29 22:36:30.268715

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9077ce18ff15"
down_revision: Union[str, None] = "8b5728efb47d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = inspector.get_table_names()

    def get_cols(table):
        if table not in existing_tables:
            return []
        return [c['name'] for c in inspector.get_columns(table)]

    def get_fks(table):
        if table not in existing_tables:
            return []
        return [f['name'] for f in inspector.get_foreign_keys(table)]

    def get_indexes(table):
        if table not in existing_tables:
            return []
        return [i['name'] for i in inspector.get_indexes(table)]

    # ### commands auto generated by Alembic - please adjust! ###
    if 'session_number' not in get_cols('sessions'):
        op.add_column("sessions", sa.Column("session_number", sa.Integer(), nullable=True))
    if 'session_date' not in get_cols('sessions'):
        op.add_column("sessions", sa.Column("session_date", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sessions", "session_date")
    op.drop_column("sessions", "session_number")
    # ### end Alembic commands ###
