"""add new saved prompts table

Revision ID: 90a962856771
Revises: 7e9bdf9d4379
Create Date: 2025-06-23 14:00:13.774721

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "90a962856771"
down_revision: Union[str, None] = "7e9bdf9d4379"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = inspector.get_table_names()

    def get_cols(table):
        if table not in existing_tables:
            return []
        return [c['name'] for c in inspector.get_columns(table)]

    def get_fks(table):
        if table not in existing_tables:
            return []
        return [f['name'] for f in inspector.get_foreign_keys(table)]

    def get_indexes(table):
        if table not in existing_tables:
            return []
        return [i['name'] for i in inspector.get_indexes(table)]

    # ### commands auto generated by Alembic - please adjust! ###
    if "saved_prompts" not in existing_tables:
        op.create_table(
            "saved_prompts",
            sa.Column("id", sa.UUID(), nullable=False),
            sa.Column("name", sa.String(length=200), nullable=True),
            sa.Column("description", sa.Text(), nullable=True),
            sa.Column("category", sa.String(length=100), nullable=True),
            sa.Column("content", sa.Text(), nullable=True),
            sa.Column("tags", sa.String(length=255), nullable=True),
            sa.Column("is_default", sa.Boolean(), nullable=True),
            sa.Column("is_public", sa.Boolean(), nullable=True),
            sa.Column("created_at", sa.DateTime(), nullable=True),
            sa.Column("updated_at", sa.DateTime(), nullable=True),
            sa.Column("usage_count", sa.Integer(), nullable=True),
            sa.Column("user_id", sa.UUID(), nullable=True),
            sa.ForeignKeyConstraint(
                ["user_id"],
                ["users.id"],
            ),
            sa.PrimaryKeyConstraint("id"),
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("saved_prompts")
    # ### end Alembic commands ###
