"""fix session run foreign key

Revision ID: a8aba4622ffc
Revises: 5194ac3a4a7c
Create Date: 2025-06-10 14:37:40.182177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8aba4622ffc'
down_revision: Union[str, None] = '5194ac3a4a7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('session_runs_user_id_fkey', 'session_runs', type_='foreignkey')
    op.create_foreign_key(None, 'session_runs', 'users', ['user_id'], ['id'])
    op.drop_constraint('sessions_user_id_fkey', 'sessions', type_='foreignkey')
    op.create_foreign_key(None, 'sessions', 'users', ['user_id'], ['id'])
    op.drop_constraint('users_user_id_key', 'users', type_='unique')
    op.drop_column('users', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_unique_constraint('users_user_id_key', 'users', ['user_id'])
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.create_foreign_key('sessions_user_id_fkey', 'sessions', 'users', ['user_id'], ['user_id'])
    op.drop_constraint(None, 'session_runs', type_='foreignkey')
    op.create_foreign_key('session_runs_user_id_fkey', 'session_runs', 'users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###
