"""fix session run foreign key

Revision ID: a8aba4622ffc
Revises: 5194ac3a4a7c
Create Date: 2025-06-10 14:37:40.182177

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a8aba4622ffc"
down_revision: Union[str, None] = "5194ac3a4a7c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = inspector.get_table_names()

    def get_cols(table):
        if table not in existing_tables:
            return []
        return [c['name'] for c in inspector.get_columns(table)]

    def get_fks(table):
        if table not in existing_tables:
            return []
        return [f['name'] for f in inspector.get_foreign_keys(table)]

    def get_indexes(table):
        if table not in existing_tables:
            return []
        return [i['name'] for i in inspector.get_indexes(table)]

    # ### commands auto generated by Alembic - please adjust! ###
    if 'session_runs_user_id_fkey' in get_fks('session_runs'):
        op.drop_constraint("session_runs_user_id_fkey", "session_runs", type_="foreignkey")
    op.create_foreign_key(None, "session_runs", "users", ["user_id"], ["id"])
    if 'sessions_user_id_fkey' in get_fks('sessions'):
        op.drop_constraint("sessions_user_id_fkey", "sessions", type_="foreignkey")
    op.create_foreign_key(None, "sessions", "users", ["user_id"], ["id"])
    if 'users_user_id_key' in get_fks('users'):
        op.drop_constraint("users_user_id_key", "users", type_="unique")
    if 'user_id' in get_cols('users'):
        op.drop_column("users", "user_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False)
    )
    op.create_unique_constraint("users_user_id_key", "users", ["user_id"])
    op.drop_constraint(None, "sessions", type_="foreignkey")
    op.create_foreign_key(
        "sessions_user_id_fkey", "sessions", "users", ["user_id"], ["user_id"]
    )
    op.drop_constraint(None, "session_runs", type_="foreignkey")
    op.create_foreign_key(
        "session_runs_user_id_fkey", "session_runs", "users", ["user_id"], ["user_id"]
    )
    # ### end Alembic commands ###
