"""Add session runs table

Revision ID: b92063665e8a
Revises: 76f1bb55dd5d
Create Date: 2025-06-08 19:42:15.741038

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b92063665e8a"
down_revision: Union[str, None] = "76f1bb55dd5d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = inspector.get_table_names()

    def get_columns(table):
        if table not in existing_tables:
            return []
        return [col['name'] for col in inspector.get_columns(table)]

    if 'users' not in existing_tables:
        op.create_table(
            "users",
            sa.Column("id", sa.UUID(), nullable=False),
            sa.Column("username", sa.String(length=255), nullable=False),
            sa.Column("password", sa.String(length=255), nullable=False),
            sa.Column("created_at", sa.DateTime(), nullable=True),
            sa.Column("updated_at", sa.DateTime(), nullable=True),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint("username"),
        )

    if 'session_runs' not in existing_tables:
        op.create_table(
            "session_runs",
            sa.Column("id", sa.UUID(), nullable=False),
            sa.Column("session_run_id", sa.String(length=50), nullable=False),
            sa.Column("session_id", sa.UUID(), nullable=False),
            sa.Column("assistant_parameters", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
            sa.Column("run_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
            sa.Column("status", sa.Enum("ACTIVE", "COMPLETED", "FAILED", name="sessionrunstatus"), nullable=True),
            sa.Column("started_at", sa.DateTime(), nullable=True),
            sa.Column("ended_at", sa.DateTime(), nullable=True),
            sa.Column("created_at", sa.DateTime(), nullable=True),
            sa.Column("updated_at", sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(["session_id"], ["sessions.id"],),
            sa.PrimaryKeyConstraint("id"),
        )

    indexes = [i['name'] for i in inspector.get_indexes('session_runs')] if 'session_runs' in existing_tables else []
    if 'ix_session_runs_session_run_id' not in indexes:
        op.create_index(op.f("ix_session_runs_session_run_id"), "session_runs", ["session_run_id"], unique=True)

    if 'presentations' in existing_tables:
        pres_columns = get_columns('presentations')
        if 'created_at' not in pres_columns:
            op.add_column("presentations", sa.Column("created_at", sa.DateTime(), nullable=True))
        if 'updated_at' not in pres_columns:
            op.add_column("presentations", sa.Column("updated_at", sa.DateTime(), nullable=True))

    if 'updated_at' not in get_columns('sessions'):
        op.add_column("sessions", sa.Column("updated_at", sa.DateTime(), nullable=True))

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sessions", "updated_at")
    op.drop_column("presentations", "updated_at")
    op.drop_column("presentations", "created_at")
    op.drop_index(op.f("ix_session_runs_session_run_id"), table_name="session_runs")
    op.drop_table("session_runs")
    op.drop_table("users")
    # ### end Alembic commands ###
