"""Add session runs table

Revision ID: b92063665e8a
Revises: 76f1bb55dd5d
Create Date: 2025-06-08 19:42:15.741038

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b92063665e8a"
down_revision: Union[str, None] = "76f1bb55dd5d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column("password", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "session_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_run_id", sa.String(length=50), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column(
            "assistant_parameters",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "run_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "COMPLETED", "FAILED", name="sessionrunstatus"),
            nullable=True,
        ),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("ended_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_session_runs_session_run_id"),
        "session_runs",
        ["session_run_id"],
        unique=True,
    )
    op.add_column(
        "presentations", sa.Column("created_at", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "presentations", sa.Column("updated_at", sa.DateTime(), nullable=True)
    )
    op.add_column("sessions", sa.Column("updated_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sessions", "updated_at")
    op.drop_column("presentations", "updated_at")
    op.drop_column("presentations", "created_at")
    op.drop_index(op.f("ix_session_runs_session_run_id"), table_name="session_runs")
    op.drop_table("session_runs")
    op.drop_table("users")
    # ### end Alembic commands ###
