"""add_subscriber_sessions

Revision ID: e195af4fccfc
Revises: f5555555555f
Create Date: 2026-07-16 11:38:07.423828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e195af4fccfc'
down_revision: Union[str, None] = 'f5555555555f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_year', table_name='cs_awards')
    op.drop_table('cs_awards')
    op.drop_table('products')
    op.drop_table('calc_history')
    op.add_column('courses', sa.Column('allow_subscriber_sessions', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'allow_subscriber_sessions')
    op.create_table('calc_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('operation_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('num1', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('num2', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('result', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('time_created', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='calc_history_pkey')
    )
    op.create_table('products',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('scraped_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='products_pkey'),
    sa.UniqueConstraint('title', name='products_title_key')
    )
    op.create_table('cs_awards',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('award_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('year_established', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('institution', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('name_length', sa.INTEGER(), sa.Computed('length(award_name)', persisted=True), autoincrement=False, nullable=True),
    sa.Column('scraped_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='cs_awards_pkey')
    )
    op.create_index('idx_year', 'cs_awards', ['year_established'], unique=False)
    # ### end Alembic commands ###
