"""changes

Revision ID: f19fc4b25b94
Revises: 2d72e810f248
Create Date: 2025-06-09 20:35:15.967542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f19fc4b25b94'
down_revision: Union[str, None] = '2d72e810f248'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('session_runs_user_id_fkey', 'session_runs', type_='foreignkey')
    op.create_foreign_key(None, 'session_runs', 'users', ['user_id'], ['user_id'])
    op.drop_constraint('sessions_user_id_fkey', 'sessions', type_='foreignkey')
    op.create_foreign_key(None, 'sessions', 'users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.create_foreign_key('sessions_user_id_fkey', 'sessions', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'session_runs', type_='foreignkey')
    op.create_foreign_key('session_runs_user_id_fkey', 'session_runs', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
