"""changes

Revision ID: f19fc4b25b94
Revises: 2d72e810f248
Create Date: 2025-06-09 20:35:15.967542

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f19fc4b25b94"
down_revision: Union[str, None] = "2d72e810f248"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = inspector.get_table_names()

    def get_cols(table):
        if table not in existing_tables:
            return []
        return [c['name'] for c in inspector.get_columns(table)]

    def get_fks(table):
        if table not in existing_tables:
            return []
        return [f['name'] for f in inspector.get_foreign_keys(table)]

    def get_indexes(table):
        if table not in existing_tables:
            return []
        return [i['name'] for i in inspector.get_indexes(table)]

    # ### commands auto generated by Alembic - please adjust! ###
    if 'session_runs_user_id_fkey' in get_fks('session_runs'):
        op.drop_constraint("session_runs_user_id_fkey", "session_runs", type_="foreignkey")
    op.create_foreign_key(None, "session_runs", "users", ["user_id"], ["id"])
    if 'sessions_user_id_fkey' in get_fks('sessions'):
        op.drop_constraint("sessions_user_id_fkey", "sessions", type_="foreignkey")
    op.create_foreign_key(None, "sessions", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "sessions", type_="foreignkey")
    op.create_foreign_key(
        "sessions_user_id_fkey", "sessions", "users", ["user_id"], ["id"]
    )
    op.drop_constraint(None, "session_runs", type_="foreignkey")
    op.create_foreign_key(
        "session_runs_user_id_fkey", "session_runs", "users", ["user_id"], ["id"]
    )
    # ### end Alembic commands ###
