"""added 'ai_instructions' column to session table

Revision ID: f2de7958d541
Revises: 7343ed3629c3
Create Date: 2025-06-03 15:30:17.822734

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f2de7958d541"
down_revision: Union[str, None] = "7343ed3629c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sessions", sa.Column("ai_instructions", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sessions", "ai_instructions")
    # ### end Alembic commands ###
