"""session roles, run summaries, user memory, knowledge chunks

Revision ID: f7a8b9c0d1e2
Revises: e6f7a8b9c0d1
Create Date: 2026-06-01

Changes:
  sessions:
    + selected_role_id  UUID FK → avatar_template_roles.id  (nullable)
    + role_label        String(100)  snapshot of role name at creation

  session_runs:
    + ai_summary    Text  (nullable) — generated by SummarizationService on stop
    + role_at_start String(100) — snapshot of role name when run started

  NEW TABLE user_memories:
    Persistent per-user learning signals that survive across sessions.
    embedding column requires pgvector extension.

  NEW TABLE knowledge_document_chunks:
    Chunked text from knowledge documents for RAG retrieval.
    embedding column requires pgvector extension.

pgvector strategy: CREATE EXTENSION IF NOT EXISTS vector — safe to run even
if already installed. If pgvector is unavailable, both migrations below will
error; in that case remove the embedding columns and re-run without them.
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'f7a8b9c0d1e2'
down_revision: Union[str, None] = 'e6f7a8b9c0d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = inspector.get_table_names()

    def get_cols(table):
        if table not in existing_tables:
            return []
        return [c['name'] for c in inspector.get_columns(table)]

    def get_fks(table):
        if table not in existing_tables:
            return []
        return [f['name'] for f in inspector.get_foreign_keys(table)]

    def get_indexes(table):
        if table not in existing_tables:
            return []
        return [i['name'] for i in inspector.get_indexes(table)]

    # pgvector: embedding columns are stored as Text (JSON-encoded float lists)
    # so this migration does NOT require the pgvector extension.
    # Vector similarity search can be layered on top later without a schema change.

    # ── sessions: role columns ────────────────────────────────────────────────
    if 'selected_role_id' not in get_cols('sessions'):
        op.add_column("sessions",
            sa.Column("selected_role_id", postgresql.UUID(as_uuid=True),
                      sa.ForeignKey("avatar_template_roles.id", name="fk_sessions_selected_role",
                                    use_alter=True, ondelete="SET NULL"),
                      nullable=True))
    if 'role_label' not in get_cols('sessions'):
        op.add_column("sessions",
            sa.Column("role_label", sa.String(100), nullable=True))

    # ── session_runs: summary + role snapshot ─────────────────────────────────
    if 'ai_summary' not in get_cols('session_runs'):
        op.add_column("session_runs",
            sa.Column("ai_summary", sa.Text, nullable=True))
    if 'role_at_start' not in get_cols('session_runs'):
        op.add_column("session_runs",
            sa.Column("role_at_start", sa.String(100), nullable=True))

    # ── user_memories ─────────────────────────────────────────────────────────
    op.create_table(
        "user_memories",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("user_id", postgresql.UUID(as_uuid=True),
                  sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False),
        sa.Column("avatar_id", postgresql.UUID(as_uuid=True),
                  sa.ForeignKey("avatars.id", ondelete="SET NULL"), nullable=True),
        sa.Column("content", sa.Text, nullable=False),
        sa.Column("importance", sa.Float, nullable=False, server_default="1.0"),
        sa.Column("embedding", sa.Text, nullable=True),  # JSON-encoded float list
        sa.Column("created_at", sa.DateTime, server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime, server_default=sa.func.now(), nullable=False),
    )
    op.create_index("ix_user_memories_user_id", "user_memories", ["user_id"])
    op.create_index("ix_user_memories_avatar_id", "user_memories", ["avatar_id"])

    # ── knowledge_document_chunks ─────────────────────────────────────────────
    op.create_table(
        "knowledge_document_chunks",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("knowledge_document_id", postgresql.UUID(as_uuid=True),
                  sa.ForeignKey("knowledge_documents.id", ondelete="CASCADE"), nullable=False),
        sa.Column("chunk_index", sa.Integer, nullable=False),
        sa.Column("chunk_text", sa.Text, nullable=False),
        sa.Column("embedding", sa.Text, nullable=True),  # JSON-encoded float list
        sa.Column("created_at", sa.DateTime, server_default=sa.func.now(), nullable=False),
    )
    op.create_index("ix_knowledge_chunks_doc_id",
                    "knowledge_document_chunks", ["knowledge_document_id"])


def downgrade() -> None:
    op.drop_table("knowledge_document_chunks")
    op.drop_table("user_memories")
    op.drop_column("session_runs", "role_at_start")
    op.drop_column("session_runs", "ai_summary")
    op.drop_column("sessions", "role_label")
    op.drop_column("sessions", "selected_role_id")
