import uuid
from datetime import datetime

from sqlalchemy import Column, DateTime, Float, ForeignKey, Integer, UniqueConstraint
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import relationship

from app.database.connection import Base


class SubscriberCourseProgress(Base):
    """W6: Tracks a subscriber's cumulative progress in a course (R82)."""
    __tablename__ = "subscriber_course_progress"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id = Column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    course_id = Column(UUID(as_uuid=True), ForeignKey("courses.id", ondelete="CASCADE"), nullable=False, index=True)
    session_run_id = Column(
        UUID(as_uuid=True),
        ForeignKey("session_runs.id", ondelete="SET NULL"),
        nullable=True,
    )
    completion_pct = Column(Float, nullable=False, default=0.0)
    time_spent_sec = Column(Integer, nullable=False, default=0)
    last_session_at = Column(DateTime, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    __table_args__ = (
        UniqueConstraint("user_id", "course_id", name="uq_subscriber_course_progress"),
    )

    user = relationship("User")
    course = relationship("Course")
    session_run = relationship("SessionRun")


class AssessmentResult(Base):
    """W6: Post-session quiz generated by GPT-4o-mini (R83)."""
    __tablename__ = "assessment_results"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    session_run_id = Column(
        UUID(as_uuid=True),
        ForeignKey("session_runs.id", ondelete="CASCADE"),
        nullable=False,
        unique=True,
        index=True,
    )
    user_id = Column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=False, index=True)
    avatar_id = Column(UUID(as_uuid=True), ForeignKey("avatars.id", ondelete="SET NULL"), nullable=True)
    quiz_questions = Column(JSONB, nullable=True)
    score = Column(Float, nullable=True)
    generated_at = Column(DateTime, default=datetime.utcnow)

    session_run = relationship("SessionRun")
    user = relationship("User")
    avatar = relationship("Avatar")
